#!/bin/bash

function cd {
  builtin cd "$@" && ls -F && echo && echo && pwd;
}


function zsh-stats() {
    fc -l 1 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n25;
}

function pause-clion() {
  kill -stop `pidof clangd`
  kill -stop `pidof java`
}

function resume-clion() {
  kill -cont `pidof java`
  kill -cont `pidof clangd`
}


function run {
  clear
  ninja $@
  ./$@
}

