#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../setup/lib/common.sh
source "$SCRIPT_DIR/../setup/lib/common.sh"
SHOW_HELP=false
parse_common_flags "$@"

SRC_FILE="$SCRIPT_DIR/my_msi_driver.cpp"
BIN_PATH="/usr/local/bin/my_msi_driver"
UNIT_PATH="/etc/systemd/system/my_msi_driver.service"
MODULES_FILE="/etc/modules-load.d/nct6775.conf"
FANCONTROL_FILE="/etc/fancontrol"

# Tunables (overridable before parse_common_flags via env, or edit here)
AIO_MODE="${AIO_MODE:-5}"          # 0 silent 1 balance 2 game 4 default 5 smart
PWM_CHANNEL="${PWM_CHANNEL:-7}"    # discovered with map-fans.sh
FAN_TACH="${FAN_TACH:-7}"
MINPWM="${MINPWM:-80}"             # stall floor measured on this board; <=64 stalls
MINTEMP="${MINTEMP:-40}"
MAXTEMP="${MAXTEMP:-70}"
MINSTART="${MINSTART:-110}"
MINSTOP="${MINSTOP:-80}"
MAXPWM="${MAXPWM:-255}"
INTERVAL="${INTERVAL:-10}"
AVERAGE="${AVERAGE:-2}"

if [[ "$SHOW_HELP" == "true" ]]; then
  cat <<'USAGE'
Usage: ./fan-control/setup-fan-control.sh [flags...]

Install fan control for MSI MEG Coreliquid S360 + Nuvoton board fans:
  - builds my_msi_driver.cpp (AIO daemon, SMART mode, feeds CPU temp over USB)
  - loads the in-kernel nct6775 driver and enables lm_sensors fancontrol
  - writes systemd units, modules-load.d and /etc/fancontrol

Discover the pwm<->fan mapping first with: sudo ./fan-control/map-fans.sh

Options:
  --uninstall   Remove everything this script installed
  --verbose     Show extra debug output
  -h, --help    Show this help message

Environment overrides:
  AIO_MODE PWM_CHANNEL FAN_TACH MINPWM MINTEMP MAXTEMP MINSTART MINSTOP MAXPWM
  INTERVAL AVERAGE   (current: AIO_MODE=$AIO_MODE PWM_CHANNEL=$PWM_CHANNEL
   FAN_TACH=$FAN_TACH MINPWM=$MINPWM MINTEMP=$MINTEMP MAXTEMP=$MAXTEMP)
USAGE
    exit 0
fi

if [[ $EUID -eq 0 ]]; then
    die "This script should not be run as root"
fi

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1${2:+ (pacman -S $2)}"
}

find_hwmon() {
    local want="$1" d
    for d in /sys/class/hwmon/hwmon*; do
        [[ -r "$d/name" ]] || continue
        # shellcheck disable=SC2053  # want is a glob pattern (e.g. 'nct*')
        if [[ "$(cat "$d/name")" == $want ]]; then
            printf '%s' "$d"
            return 0
        fi
    done
    return 1
}

install_aio_driver() {
    log "Installing AIO driver (mode=$AIO_MODE)"
    require_cmd g++ gcc
    [[ -f "$SRC_FILE" ]] || die "Source not found: $SRC_FILE"

    log_step "Building $SRC_FILE"
    local out
    out=$(mktemp)
    run_cmd g++ "$SRC_FILE" -Wall -Wextra -std=c++17 -lhidapi-hidraw -lsensors -o "$out"

    log_step "Installing $BIN_PATH"
    run_cmd sudo install -m755 "$out" "$BIN_PATH"
    rm -f "$out"

    log_step "Writing $UNIT_PATH"
    local tmp
    tmp=$(mktemp)
    cat > "$tmp" <<EOF
[Unit]
Description=MSI MEG Coreliquid S360 fan control driver
After=multi-user.target

[Service]
Type=simple
ExecStart=$BIN_PATH -M $AIO_MODE startd
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
    run_cmd sudo install -m644 "$tmp" "$UNIT_PATH"
    rm -f "$tmp"

    run_cmd sudo systemctl daemon-reload
    run_cmd sudo systemctl enable my_msi_driver.service
    # enable --now won't restart an already-running unit, and we just
    # replaced the binary it exec'd
    run_cmd sudo systemctl restart my_msi_driver.service
    log_step "my_msi_driver.service active: $(systemctl is-active my_msi_driver.service)"
}

install_board_fans() {
    log "Loading nct6775 and configuring fancontrol"
    require_cmd modprobe

    run_cmd sudo modprobe nct6775
    log_step "Writing $MODULES_FILE"
    echo "nct6775" | run_cmd sudo tee "$MODULES_FILE" >/dev/null

    local nct core
    nct=$(find_hwmon 'nct*') || die "nct chip not found after modprobe"
    core=$(find_hwmon 'coretemp') || die "coretemp hwmon not found"

    local nct_base core_base nct_path core_path nct_name core_name
    nct_base=$(basename "$nct")
    core_base=$(basename "$core")
    nct_path=$(readlink -f "$nct/device" | sed 's|^/sys/||')
    core_path=$(readlink -f "$core/device" | sed 's|^/sys/||')
    nct_name=$(tr ' =\t' '___' < "$nct/name")
    core_name=$(tr ' =\t' '___' < "$core/name")

    [[ -e "$nct/pwm$PWM_CHANNEL" ]] || die "pwm$PWM_CHANNEL missing under $nct (run map-fans.sh)"
    [[ -r "$nct/fan${FAN_TACH}_input" ]] || die "fan${FAN_TACH}_input missing under $nct"

    log_step "Writing $FANCONTROL_FILE ($nct_base/pwm$PWM_CHANNEL <- $core_base/temp1)"
    local tmp
    tmp=$(mktemp)
    cat > "$tmp" <<EOF
# Generated by fan-control/setup-fan-control.sh
INTERVAL=$INTERVAL
DEVPATH=$nct_base=$nct_path $core_base=$core_path
DEVNAME=$nct_base=$nct_name $core_base=$core_name
FCTEMPS=$nct_base/pwm$PWM_CHANNEL=$core_base/temp1_input
FCFANS=$nct_base/pwm$PWM_CHANNEL=$nct_base/fan${FAN_TACH}_input
MINTEMP=$nct_base/pwm$PWM_CHANNEL=$MINTEMP
MAXTEMP=$nct_base/pwm$PWM_CHANNEL=$MAXTEMP
MINSTART=$nct_base/pwm$PWM_CHANNEL=$MINSTART
MINSTOP=$nct_base/pwm$PWM_CHANNEL=$MINSTOP
MINPWM=$nct_base/pwm$PWM_CHANNEL=$MINPWM
MAXPWM=$nct_base/pwm$PWM_CHANNEL=$MAXPWM
AVERAGE=$nct_base/pwm$PWM_CHANNEL=$AVERAGE
EOF
    run_cmd sudo install -m644 "$tmp" "$FANCONTROL_FILE"
    rm -f "$tmp"

    run_cmd sudo systemctl restart fancontrol.service
    run_cmd sudo systemctl enable fancontrol.service
    log_step "fancontrol.service active: $(systemctl is-active fancontrol.service)"
}

uninstall() {
    log "Uninstalling fan control"
    run_cmd_may_fail sudo systemctl disable --now fancontrol.service
    run_cmd_may_fail sudo systemctl disable --now my_msi_driver.service
    run_cmd_may_fail sudo rm -f "$UNIT_PATH" "$FANCONTROL_FILE" "$MODULES_FILE" "$BIN_PATH"
    run_cmd_may_fail sudo systemctl daemon-reload
    run_cmd_may_fail sudo rmmod nct6775
    log "Removed. Current fan state was restored to BIOS auto mode where possible."
    log "Done"
    exit 0
}

[[ "$UNINSTALL" == "true" ]] && uninstall

install_aio_driver
install_board_fans

log "Done"
log "Re-run this script after a BIOS update or if hwmon numbering changes"
log "(fancontrol refuses to start when DEVPATH no longer matches)."
