#!/bin/bash

file="$1"
timezone="$TZ"
site="$2"

curdir=$(dirname "$0")
isup="$curdir/../bin/isup";

if [ -z "$timezone" ]; then
    timezone="Asia/Tehran";
fi

if [ -z "$file" ]; then
    file="/tmp/network-status.log"
fi

while true; do

    if $isup https "$site" >/dev/null; then
        datetime=$(TZ="$timezone" date)
        country=$(env myip country)
        echo "$datetime: Network Connected ($country)" | tee -a "$file";
    else
        datetime=$(TZ="$timezone" date)
        echo "$datetime: Network Not connected." | tee -a "$file";
    fi;

    sleep 5s;
done
