#!/usr/bin/env python3

from nftables import Nftables
from nftables import json
import math

def convert_size(size_bytes):
    if size_bytes == 0:
        return 0, "B"
    size_name = ("B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return s, size_name[i]


nft = Nftables()
nft.set_json_output(True)
_, output, _ = nft.cmd("list counters")
j = json.loads(output)

print("{:>20}   {:>10}  {:>10}  {:>10}".format("Counter name", "Count", "Bytes", "Packets"))
print("{:>20}   {:>10}  {:>10}  {:>10}".format("-" * 20, "-" * 10, "-" * 10, "-" * 10))
for i in range(len(j['nftables'])):
    if i == 0:
        continue
    counter = j['nftables'][i]["counter"]
    packets = counter["packets"]
    name = counter["name"]
    counter_bytes = counter["bytes"]
    count, count_name = convert_size(counter_bytes)
    print("{:>20}:  {:>6.1f} {:<3}  {:>10}  {:>10,}".format(name, count, count_name, counter_bytes, packets))

