#!/bin/bash

curdir=$(dirname "$0")

lo_socks_fwmark=0xff
table_id=153
redsocks_bin="$HOME/bin/redsocks2"
redsocks_config="$curdir/tproxy2socks-redsocks.conf"
redsocks_pid="/tmp/tproxy2socks/redsocks2.pid"

# rp_filer = https://sysctl-explorer.net/net/ipv4/rp_filter/

mkdir -p "$(dirname "$redsocks_pid")";

function prepare_proxy {
    if [ ! -f "$redsocks_bin" ]; then
        install_redsocks;
    fi

    for dir in /proc/sys/net/ipv4/conf/*; do
        if [ -d "$dir" ]; then
            dirname=$(basename $dir)
            sudo sysctl net/ipv4/conf/$dirname/rp_filter=0
        fi
    done

    sudo ip rule add fwmark $lo_socks_fwmark table $table_id
    sudo ip route add local default dev lo table $table_id
    sudo tproxy2socks.nft

    echo
    echo "Redsocks Executable:  $redsocks_bin"
    echo "Redsocks Config file: $redsocks_config"
    echo "Redsocks pid file:    $redsocks_pid"
    echo
}

function enable_proxy {
    prepare_proxy;
    $redsocks_bin -c "$redsocks_config" -p "$redsocks_pid"
    disable_proxy;
}

function disable_proxy {
    sudo nft delete table inet socks;
    sudo ip route delete local default dev lo table $table_id
    sudo ip rule delete fwmark $lo_socks_fwmark table $table_id


    for dir in /proc/sys/net/ipv4/conf/*; do
        if [ -d "$dir" ]; then
            dirname=$(basename $dir)
            sudo sysctl net/ipv4/conf/$dirname/rp_filter=2
        fi
    done
}

function enable_background_proxy {
    prepare_proxy;
    $redsocks_bin -c "$redsocks_config" -p "$redsocks_pid" &
}

function disable_background_proxy {
    disable_proxy;
    kill $(cat "$redsocks_pid");
    rm -f "$redsocks_pid";
}


function install_redsocks {
    destination="$1"
    if [ -z "$destination" ]; then
        destination=$(mktemp -d);
    fi
    git clone https://github.com/semigodking/redsocks.git --recursive --depth=1 "$destination"
    cwd="$PWD"
    builtin cd "$destination"
    make DISABLE_SHADOWSOCKS=true
    cp ./redsocks2 "$redsocks_bin"
    builtin cd "$cwd"
    if command -v strip >/dev/null; then 
        strip "$redsocks_bin";
    fi
}

case $1 in
    enable)
        enable_proxy
        ;;
    enable-background)
        enable_background_proxy
        ;;
    disable)
        disable_proxy
        ;;
    disable-background)
        disable_background_proxy
        ;;
    restart|reset|restart-background)
        disable_background_proxy
        enable_background_proxy
        ;;
    is-running-in-background)
        if [ -f "$redsocks_pid" ]; then
            exit 0;
        else
            exit 1;
        fi
        ;;
    reload|restart|reset)
        disable_proxy
        enable_proxy
        ;;
    install)
        install_redsocks $2
        ;;
    *)
        echo "tproxy2socks enable                     # enables the tproxy"
        echo "tproxy2socks enable-background          # enables the tproxy in background"
        echo "tproxy2socks disable                    # disables the transparent proxy"
        echo "tproxy2socks disable-background         # disables the transparent proxy that is run in the background"
        echo "tproxy2socks reload/reset/restart       # disables and then enable the transparent proxy"
        echo "tproxy2socks install [dir]              # install redsocks"
        echo "tproxy2socks is-running-in-background   # check if it's running in the background"
        ;;
esac;
