#!/bin/bash

lo_v2ray_fwmark=0xff
table_id=153

# rp_filer = https://sysctl-explorer.net/net/ipv4/rp_filter/

function enable_proxy {
    for dir in /proc/sys/net/ipv4/conf/*; do
        if [ -d "$dir" ]; then
            dirname=$(basename $dir)
            sudo sysctl net/ipv4/conf/$dirname/rp_filter=0
        fi
    done

    sudo ip rule add fwmark $lo_v2ray_fwmark table $table_id
    sudo ip route add local default dev lo table $table_id
    sudo tproxy-to-v2ray.nft
}

function disable_proxy {
    sudo nft delete table inet v2ray;
    sudo ip route delete local default dev lo table $table_id
    sudo ip rule delete fwmark $lo_v2ray_fwmark table $table_id


    for dir in /proc/sys/net/ipv4/conf/*; do
        if [ -d "$dir" ]; then
            dirname=$(basename $dir)
            sudo sysctl net/ipv4/conf/$dirname/rp_filter=2
        fi
    done
}

case $1 in
    enable)
        enable_proxy
        ;;
    disable)
        disable_proxy
        ;;
    reload|restart|reset)
        disable_proxy
        enable_proxy
        ;;
    *)
        echo "tproxy enable # enables the tproxy"
        echo "tproxy disable # disables the transparent proxy"
        echo "tproxy reload/reset/restart # disables and then enable the transparent proxy"
        ;;
esac;
