[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#191724'
cursor = '#e0def4'

[colors.vi_mode_cursor]
text = '#191724'
cursor = '#ebbcba'

[colors.search.matches]
foreground = '#26233a'
background = '#31748f'

[colors.search.focused_match]
foreground = '#26233a'
background = '#ebbcba'

[colors.footer_bar]
foreground = '#26233a'
background = '#e4e3e8'

[colors.hints.start]
foreground = '#26233a'
background = '#9ccfd8'

[colors.hints.end]
foreground = '#26233a'
background = '#9ccfd8'

[colors.selection]
text = '#e0def4'
background = '#403d52'


[colors.normal]
black   = '#26233a'
red     = '#eb6f92'
green   = '#31748f'
yellow  = '#f6c177'
blue    = '#9ccfd8'
magenta = '#c4a7e7'
cyan    = '#ebbcba'
white   = '#e0def4'


[colors.bright]
black   = '#6e6a86'
red     = '#eb6f92'
green   = '#31748f'
yellow  = '#f6c177'
blue    = '#9ccfd8'
magenta = '#c4a7e7'
cyan    = '#ebbcba'
white   = '#e0def4'


[colors.dim]
black   = '#26233a'
red     = '#eb6f92'
green   = '#31748f'
yellow  = '#f6c177'
blue    = '#9ccfd8'
magenta = '#c4a7e7'
cyan    = '#ebbcba'
white   = '#e0def4'
