#!/usr/bin/bash

# usage will be like this:
#   cppide PROJECT_NAME

if [ $# -eq 0 ]; then
  tmpdir=$(mktemp -d)
else
  tmpdir=$1
fi;

tmpdir=$(realpath ${tmpdir});
window="cpp-$(basename $(realpath .))-$((1 + RANDOM % 10000000))"

tmux new -s ${window} -d -c "${tmpdir}"
#tmux split-window -t ${window} -h
#tmux select-pane -t ${window}.right
#tmux resize-pane -t ${window}.right -R 20
#tmux send-keys -t ${window}.left "cd ${tmpdir}" C-m
#tmux send-keys -t ${window}.right "cd ${tmpdir}" C-m


#tmux send-keys -t ${window}.right "find . -name '*.cpp' | entr -cs 'make && ./a.out'" C-m
#tmux split-pane -t ${window}.right -v
#tmux send-keys -t ${window}.bottom-right "cd ${tmpdir}" C-m
#tmux send-keys -t ${window}.bottom-right "touch main.s" C-m
#tmux send-keys -t ${window}.bottom-right "find ${tmpdir} -name \"*.s\" | entr -cs \"clear; cat ${tmpdir}/main.s\"" C-m
#tmux send-keys -t ${window}.left "${EDITOR} ${tmpdir}/main.cpp" C-m
#tmux select-pane -t ${window}.left

tmux send-keys -t $window "$EDITOR $tmpdir" C-m
tmux attach -t ${window}

