#!/usr/bin/bash

tmpdir=$(mktemp -d)
window="cpp-$((1 + RANDOM % 10))"

tmux new -s ${window} -d -c "${tmpdir}"
tmux split-window -t ${window} -h
tmux select-pane -t ${window}.right
tmux resize-pane -t ${window}.right -R 20
tmux send-keys -t ${window}.left "cd ${tmpdir}" C-m
tmux send-keys -t ${window}.right "cd ${tmpdir}" C-m
tmux send-keys -t ${window}.right 'touch main.cpp' C-m
tmux send-keys -t ${window}.right 'echo "#include <iostream>\n\nint main() {\n\tusing namespace std;\n\tcout << \"hello world\" << endl;\n\treturn 0;\n}\n" > main.cpp' C-m
tmux send-keys -t ${window}.right 'echo "all:\n\tg++ -std=c++2a -g -O3 main.cpp\n\tg++ -std=c++2a -S -fverbose-asm -O3 main.cpp" > Makefile' C-m
tmux send-keys -t ${window}.right "find . -name '*.cpp' | entr -cs 'make && ./a.out'" C-m
tmux split-pane -t ${window}.right -v
tmux send-keys -t ${window}.bottom-right "cd ${tmpdir}" C-m
tmux send-keys -t ${window}.bottom-right "touch main.s" C-m
tmux send-keys -t ${window}.bottom-right 'find . -name "*.s" | entr -cs "clear; cat main.s"' C-m
tmux send-keys -t ${window}.left 'vim main.cpp' C-m
tmux select-pane -t ${window}.left
tmux attach -t ${window}

