#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "SpaceVim"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    default_indent = 4
    expand_tab = true
    enable_vimfiler_welcome = false
    filemanager = "vimfiler"
    enable_filetree_gitstatus = true

# Enable autocomplete layer
[[layers]]
	name = 'autocomplete'
	auto-completion-return-key-behavior = "complete"
	auto-completion-tab-key-behavior = "smart"

[[layers]]
	name = 'shell'
	default_position = 'top'
	default_height = 30

[[layers]]
	name = "lang#c"
    # enable_clang_syntax_highlight = true
    libclang_path = "/usr/lib/libclang.so"
	clang_executable = "/usr/bin/clang"
	[layer.clang_std]
		c = "c18"
		cpp = "c++20"
		objc = "c18"
		objcpp = "c++20"

[[layers]]
    name="format"


[[layers]]
    name="tools"

[[layers]]
    name="denite"

[[layers]]
    name="git"

[[layers]]
    name="gtags"
    gtagslabel="pygments"

[[layers]]
    name="lsp"
    filetypes= [
        "cpp",
        "c"
    ]
    enabled_clients = ['clangd']
    [layers.override_cmd]
        cpp = ["clangd", "-std=c++20", "-fmodules-ts"]

[[layers]]
    name="ui"
    enable_sidebar = true


[[layers]]
    name="shell"
    default_position = "bottom"
    default_height = 30

[[layers]]
    name="debug"

[[layers]]
    name = "VersionControl"
