# Noctalia config — system monitor widgets on bar

[bar.default]
start = [ "launcher", "wallpaper", "workspaces",  "spacer1", "cpu", "spacer2", "ram", "spacer3", "gpu", "spacer4", "network_rx", "network_tx" ]
center = [ "clock" ]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]

[widget.spacer1]
type = "spacer"

[widget.spacer2]
type = "spacer"

[widget.spacer3]
type = "spacer"

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"

[widget.ram]
type = "sysmon"
stat = "ram_used"

[widget.network_rx]
type = "sysmon"
stat = "net_rx"

[widget.network_tx]
type = "sysmon"
stat = "net_tx"

[widget.gpu]
type = "sysmon"
stat = "gpu_usage"

[widget.spacer4]
type = "spacer"
