# [colors]
# [colors.primary]
# background = "0x282828"
# foreground = "0xd4be98"
# 
# [colors.normal]
# black = "0x3c3836"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xd8a657"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xd4be98"
# 
# [colors.bright]
# black = "0x3c3836"
# red = "0xea6962"
# green = "0xa9b665"
# yellow = "0xd8a657"
# blue = "0x7daea3"
# magenta = "0xd3869b"
# cyan = "0x89b482"
# white = "0xd4be98"

# Themes from: https://github.com/alacritty/alacritty-theme
general.import = [
    "~/.config/alacritty/alacritty-theme/themes/carbonfox.toml"
    # "~/.config/alacritty/alacritty-theme/themes/rose_pine.toml"
    # "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/alacritty-theme/themes/tomorrow_night.toml"
    # "~/.config/alacritty/alacritty-theme/themes/konsole_linux.toml"
    # "~/.config/alacritty/alacritty-theme/themes/hyper.toml"
    # "~/.config/alacritty/alacritty-theme/themes/breeze.toml"
]

[terminal]
shell = "/usr/bin/nu"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 11

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.66"


[window]
dimensions.columns = 115
dimensions.lines = 50
padding.x = 16
padding.y = 14
decorations = "none"
opacity = 0.7
dynamic_padding = true
blur = true
resize_increments = true # doesn't work on Wayland yet

[scrolling]
history=100000

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]

# [[hints.enabled]]
# regex = "[^ ]+\\.(c|h)pp:\\d+:\\d+"
# command = { program = "code", args = [ "--goto" ] }
# mouse = { enabled = true }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 400
unfocused_hollow = true
thickness = 0.1

[mouse]
hide_when_typing = false
